{{- $service_name := .Values.service_name -}}
{{- $namespace := .Values.namespace -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $service_name }}-virtual-service
  namespace: {{ $namespace }}
spec:
  hosts:
  - {{ .Values.virtual_service.hosts }}
  gateways:
  - {{ .Values.virtual_service.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtual_service.prefix }}
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ .Values.service_name }}-svc
