apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service_name }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.service.port_name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ .Values.service_name }}
